### ISSUE TITLE
ecloop make: clang: No such file or directory make: *** [Makefile:14: build] Error 127

### ISSUE THREAD

**Issue by paveliym** [vladkens/ecloop#4]
1) I can't install Ubuntu on a laptop wsl
```
make: clang: No such file or directory make:
[Makefile:14: build] Error 127
```

2) I can't install Linux Mint on a PC
```
make: clang: No such file or directory make:
[Makefile:14: build] Error 127
```

3) VMware® Workstation 17 laptop
Kali Linux
everything works

tell me how to fix the error:
```
make: clang: No such file or directory
make: *** [Makefile:14: build] Error 127
```

the thing is that make goes into other programs
ecctools keysubtracter everything works but in ecloop it doesn't work what's the problem?

**Comment by vladkens** [comment]
Hi, @paveliym.

You should to install clang with `apt update && apt install clang`.

Or you can just pull latest version where I added `gcc` fallback. Here steps how I manage to run it on Windows: https://github.com/vladkens/ecloop?tab=readme-ov-file#build-on-windows-with-wsl

**Comment by paveliym** [comment]
> Привет,@paveliym.
> 
> Вам следует установить Clang с помощью `apt update && apt install clang`.
> 
> Или вы можете просто скачать последнюю версию, в которую я добавил `gcc`откат. Вот шаги, как мне удалось запустить его на Windows: https://github.com/vladkens/ecloop?tab=readme-ov-file#build-on-windows-with-wsl

Thank you, everything worked!
![Снимок экрана 2024-12-19 011306](https://github.com/user-attachments/assets/c0bc2cf1-07be-4e0a-8f1c-956c9ed7f1b1)
